src/node-file-trace.js, test/unit.test.js, test/unit/ts-filter/actual.js, test/unit/ts-filter/input.js, test/unit/ts-filter/node_modules/pkg/dep.js, test/unit/ts-filter/node_modules/pkg/index.js, test/unit/ts-filter/node_modules/pkg/index.ts, test/unit/ts-filter/output.js
This fixes up the `ts: true` option (which affects the resolver and tracing to support `.ts` files) to ensure that `.ts` files emitted as assets are not in turn traced as dependencies when they are contained in `node_modules`.
This should, with some luck, fix the current front issue.
=> Do not trace .ts files in node_modules

package.json, test/integration.test.js
We use these settings in the [now-builders](https://github.com/zeit/now-builders/blob/0d04440f0f8fc6c3dd6bd9cf8886528c5d3ca5db/package.json#L21) repo because there are sometimes problems running tests concurrently.
This seems to fix the broken tests on master.
=> Fix tests to run in band + verbose

src/resolve-dependency.js, test/unit/tsx/dep.tsx, test/unit/tsx/input.js, test/unit/tsx/lib.ts, test/unit/tsx/lib.tsx, test/unit/tsx/output.js
This adds support for `.tsx` file resolution tracing.
We could also consider adding a `jsx: true` option similarly if this is desired for `now-node`.
This should resolve the issue seen in https://github.com/zeit/node-file-trace/issues/10, although there may also be a resolver component of that issue in the now/node integration there too.
=> Support tsx resolution tracing

node-file-trace.d.ts
This adds the log option to the typing of the library.
=> Add log option to types

src/node-file-trace.js, src/resolve-dependency.js
This changes the resolver FS to use direct stat calls instead of going straight to a `read` call. Now that statting is part of the base FS API this makes more sense.
=> Use statting instead of read in resolver

.github/CODEOWNERS
We need to make sure PRs are reviewed before merging.
Adding Luc to codeowners.
=> Add lucleray to codeowners

node-file-trace.d.ts, src/analyze.js, src/node-file-trace.js, test/unit.test.js, test/unit/mixed-esm-cjs/commonjs-module.js, test/unit/mixed-esm-cjs/ecmascript-module.js, test/unit/mixed-esm-cjs/input.js, test/unit/mixed-esm-cjs/output.js, test/unit/require-esm/input.js, test/unit/require-esm/output.js
This adds support for mixing ESM and CJS so that we have feature parity with `ncc`, which is basically `webpack`.
This will fix all the issues that were reported in the latest release:
- https://spectrum.chat/zeit/general/now-deploys-suddenly-not-working~a052cb8f-e95e-4eef-9e81-5e799d1e5ef4
- https://spectrum.chat/zeit/now/did-you-forget-to-add-it-to-dependencies-in-package-json~6b370740-866c-4404-bdcc-cc51a3bc9aec
- https://spectrum.chat/zeit/now/cannot-build-ts-api-with-now-node-anymore~a24f6eb3-201a-4ecb-8688-94b4a56d4abe
- https://github.com/zeit/now-builders/issues/791
I spoke with Timer and it sounds like Next.js might want to follow the Node.js behavior. If that's the case maybe we don't want this PR to land. We need to discuss with the whole team.
Perhaps we should enable …
=> Add support for mixed ESM and CJS via `mixedModules` flag

src/analyze.js, test/unit/esm-export-wildcard/all.js, test/unit/esm-export-wildcard/input.js, test/unit/esm-export-wildcard/output.js, test/unit/esm-export-wildcard/week.js
This PR fixes the syntax `export * from './week'` which should include week.js in the output files.
Related to https://github.com/zeit/now-builders/issues/851
=> Fix esm export wildcard/asterisk syntax, ie `ExportAllDeclaration`

src/node-file-trace.js
I tested this one on Windows and it fixes the issue described in https://github.com/zeit/now-builders/issues/855
We will need to add CI for Windows in order to prevent regressions.
=> Fix windows symlink so it doesn't throw

azure-pipelines.yml, azure-prepare.js
This fixes azure pipelines so we can test `node-file-trace` in Windows CI.
Prior to this PR, you can see how the CI fails as-is on the `yarn install` step: https://dev.azure.com/zeit-builds/Node.js%20File%20Trace/_build/results?buildId=1016
This PR removes integration tests (only when running Windows CI) that don't support windows. For example, some spawn `rsync` and make assumptions about the system.
=> Use windows image for azure pipelines

.gitignore, azure-pipelines.yml, azure-prepare.js, jest.config.js, src/node-file-trace.js, src/resolve-dependency.js, src/utils/get-package-base.js, src/utils/special-cases.js, test/integration.test.js, test/integration/typescript.js, test/unit.test.js, test/unit/ts-filter/input.js
Previously, Azure Pipline was not running tests. It would only run `yarn install`. 
This PR fixes that so the tests are also run.
Fixes #31
=> Update azure-pipelines.yml to fix Windows CI

azure-prepare.js, package.json, src/utils/special-cases.js, test/integration/bull.js, yarn.lock
=> Add special case for `bull`

package.json, src/utils/special-cases.js, test/integration/uglify.js, yarn.lock
Related to https://github.com/zeit/now-builders/issues/903
=> Fix `uglify-js` special case

src/analyze.js, src/utils/static-eval.js, test/unit/webpack-node/input.js, test/unit/webpack-node/level1/a.b.js, test/unit/webpack-node/level1/c.d.js, test/unit/webpack-node/level1/level2/level3/page.js, test/unit/webpack-node/output.js
This patches multiple bugs with our static evaluator:
- `MemberExpression` did not handle `computed: true` properties when encountered
- `BinaryExpression` returned wrong value for `A || UNKNOWN -> A if A is truthy` case
- `ObjectExpression` did not wrap computed value in `{ value: ... }` for `walk` compatibility
The sum of these changes allow us to support webpack-style `target: 'node'` emitted `require`s!
=> Support webpack-style Node requires

.github/workflows/ci.yml
Per @ethomson, we can prevent double runs by disabling CI for tags.
https://twitter.com/ethomson/status/1163497426570764288?s=20
=> Prevent CI for tags

package.json, src/utils/special-cases.js, test/integration/argon2.js, windows-prepare.js, yarn.lock
Fixes #45
This package doesn't seem to work on Windows so I excluded from the Windows CI.
=> Fix `argon2` with special case

node-file-trace.d.ts
Updates the types for typescript.
Is required for https://github.com/zeit/now/pull/2926
=> Update typescript types

src/analyze.js, src/node-file-trace.js
Today, any time acorn fails to parse a source file, it skips the file and there is no way to tell if the bug is acorn or the user has a syntax error. This PR adds a warning when acorn fails to parse the source file.
I confirmed this emits a warning with `fast-glob` (mentioned in #55).
```js
const trace = require('/Users/styfle/Code/zeit/node-file-trace');
trace(['fast-glob/out/index.js'], {
ts: true,
mixedModules: true,
log: true
}).then(o => {
console.log('FILELIST:')
console.log(o.fileList.join('\n'));
console.log('\n');
if (o.warnings.length > 0) {
console.log('WARNINGS:');
console.log(o.warnings);
}
}).catch(e => { 
console.error(e)
});
```
=> Add warning on parser error

test/integration/firebase.js
Closes #58
It turns out this is not a bug in `@zeit/node-file-trace` but in fact, a bug with `@now/next` which is why it was failing at build time with webpack errors.
Changing from `@now/next` to `@now/node` works.
Let's just add this test to make sure we don't ever regress.
=> Add firebase/database to integration test

.github/CODEOWNERS
Since this package is used for `@now/next`, we should have a Next.js code owner too.
=> Add @Timer to codeowners

test/ecmascript.test.js, test/ecmascript/README.md, test/ecmascript/data-common.json, test/ecmascript/data-es2016plus.js, test/ecmascript/data-es5.js, test/ecmascript/data-es6.js, test/ecmascript/data-esintl.js, test/ecmascript/data-esnext.js
This adds a massive [test suite](https://github.com/kangax/compat-table) that powers [https://kangax.github.io](https://kangax.github.io/compat-table/es6/) to make sure we can upgrade `acorn` without regressing in the future.
It also confirms that `try/catch` is not parsed properly as @Timer found last week.
I also added a README so the next person who needs to update the test suite can do so easily.
=> Add the kangax ecmascript feature test suite

src/analyze.js, test/unit/esm-dynamic-import/dep.js, test/unit/esm-dynamic-import/input.js, test/unit/esm-dynamic-import/output.js, test/unit/esm-dynamic-import/package.json
This PR adds support for dynamic `import()` expressions.
- [Node.js Docs](https://nodejs.org/api/esm.html#esm_code_import_code_expressions)
- [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports)
=> Add support for dynamic `import()` expressions

package.json, src/cli.js, test/cli.test.js
I often use this script when debugging so might as well add it as a CLI.
- `nft print index.js` - useful for debugging by printing to stdout
- `nft build index.js` - similar to ncc which will generate a `dist` directory
This will be released as experimental and the output could change at any time without following semver.
=> Add experimental CLI

test/integration/bull.js
Something seems wrong with GitHub Actions so this will log if the environment variable (secret) is not assigned and skip the bull integration test.
=> Add logging to bull integration test

test/integration/bull.js
Follow up to #82 
This will skip the bull integration test if the environment variable secret is not found.
This happens when a PR is submitted from someone outside the ZEIT GitHub Org and GH Actions omits secrets from CI.
=> Skip bull test when connection string is missing

package.json, src/utils/special-cases.js, test/integration/semver.js, yarn.lock
The `semver` package changed in version 7 to use a [dynamic/lazy loading](https://github.com/npm/node-semver/pull/295) index file.
I first first spotted this breaking change in [Package Phobia](https://github.com/styfle/packagephobia/pull/494).
This PR adds a special case to statically analyze the `preload.js` entry point which is effectively what the `index.js` entry point used to be prior to version 7.
See the [changelog](https://github.com/npm/node-semver/blob/master/CHANGELOG.md):
> Add require('semver/preload') to load the entire module without using lazy getter methods.
=> Add special case for semver@7

src/resolve-dependency.js, test/unit/dot-dot/dir/dot-dot-req.js, test/unit/dot-dot/index.js, test/unit/dot-dot/input.js, test/unit/dot-dot/output.js
This fixes up tracing for `require('..')` without a trailing slash, which was resulting in some inaccurate analysis.
=> Fixup dot dot require

src/resolve-dependency.js
Currently `process` and `sys` give errors, when they are valid Node.js builtins (since they are not listed by repl).
This adds them as exceptions to avoid the unnecessary warning messages.
=> Add missing builtins

readme.md, src/node-file-trace.js
This provides a `cache` option which stores the stat, symlink and file cache between runs for reuse when the file system is known to not have any changes between runs.
=> Implement simple cache persistence between traces

readme.md, src/analyze.js, src/node-file-trace.js, test/unit.test.js, test/unit/basic-analysis-require/dep.js, test/unit/basic-analysis-require/input.js, test/unit/basic-analysis-require/output.js
This PR allows a new `analysis` option permitting an object of analysis features to turn on or off.
Useful for when the full expression analysis isn't needed and a fast-pass analysis is suitable.
=> Allow configurable analysis

readme.md
This keeps things open to change paths without a major release to eg support TypeScript style paths as @styfle previously mentioned.
=> [docs] Note paths as an experimental feature

package.json
The `passport-trakt` package is only used for a test, its not needed a runtime.
=> Move passport-trakt to devDependencies

readme.md
Resolves https://github.com/zeit/node-file-trace/issues/103 and https://github.com/zeit/node-file-trace/issues/73.
=> docs: Better document hooks and TypeScript support

package.json, yarn.lock
In PR #106 , `node-gyp-build` was added as a devDependency but it needs to be a dependency as seen in this PR https://github.com/zeit/now/pull/4407 that updates `@vercel/node` and `@vercel/next`.
=> Fix dependency `node-gyp-build`

readme.md, src/analyze.js, src/node-file-trace.js, src/utils/wrappers.js, test/ecmascript.test.js, test/integration.test.js, test/unit.test.js, test/unit/webpack-wrapper-strs-namespaces/input.js
This adds support for a `processCwd` configuration option, including updating the current Webpack test case to use a `path.join(process.cwd()` expression to ensure this is correctly locating assets.
=> Support a processCwd option

package.json, src/utils/wrappers.js, test/integration/polyfill-library.js, yarn.lock
Fixes #122 where AST nodes with a null `init` property were not being properly checked.
@styfle in terms of using typing to catch these sorts of bugs, this is where ESTree definitions would help... but short of that we should just be very careful on review of these AST cases.
=> Handle null init check

node-file-trace.d.ts
Added `processCwd` in #120 but forgot to add the typescript type.
=> Add missing `processCwd` type

.github/workflows/ci.yml
Currently, CI takes about 10 minutes max to complete.
This PR adds a 15 minute timeout in the case where a PR introduces and infinite loop, such as #129.
=> [ci] Add 15 minute timeout

src/resolve-dependency.js, test/unit/file-folder-slash/file-folder.js, test/unit/file-folder-slash/file-folder/index.js, test/unit/file-folder-slash/input.js, test/unit/file-folder-slash/output.js
This fixes up the resolution of specifiers with a trailing slash to ensure they skip file resolution when there exists a file by the same name.
Fixes https://github.com/vercel/node-file-trace/issues/127
=> Fix trailing slash handling

package.json, src/node-file-trace.ts, tsconfig.json
Follow up to #133
- Add `prepublishOnly` so we dont forget to compile before publishing to npm
- Add missing return type from nodeFileTrace() function
- Add a few [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) for faster compilation
=> Additional TypeScript Cleanup

jest.config.js, package.json, src/index.ts
- Created `index.ts` file as the main entrypoint so we can selectively export types, etc
- Fixed code coverage which was not pattern matching any files
- Added coverage threshold so CI fails if we ever drop below our current coverage
=> Fix ts exports and code coverage

readme.md
Version [0.8.0](https://github.com/vercel/node-file-trace/releases/tag/0.8.0) introduced the named export but the docs were not updated. This PR updates the docs to match the correct usage.
Fixes #140
=> Fix usage in readme.md

LICENSE, package.json, readme.md, yarn.lock
- Rename package from `@zeit/node-file-trace` to `@vercel/nft`
- Rename repository from `vercel/node-file-trace` to `vercel/nft` (will do once merged)
- Update company name in LICENSE
- Remove unused `@zeit/ncc` dev dependency
=> Rename package to @vercel/nft

src/analyze.ts, test/unit/asset-fs-array-expr/asset1.txt, test/unit/asset-fs-array-expr/input.js, test/unit/asset-fs-array-expr/output.js
This fixes up the array expression emission porting the same approach from https://github.com/vercel/webpack-asset-relocator-loader/pull/106.
=> Fixup array expression emission

package.json
This includes support for optional chaining so should fix those errors in analysis.
=> Bump minimum acorn version to @7.4.1

package.json, src/analyze.ts, yarn.lock
Upgrades Acorn and plugins to 8.1.0.
Fixes https://github.com/vercel/nft/issues/151.
=> deps: Acorn upgrade

readme.md, src/node-file-trace.ts, src/resolve-dependency.ts, src/types.ts, test/unit/exports-nomodule/input.js, test/unit/exports-nomodule/no.js, test/unit/exports-nomodule/node.js, test/unit/exports-nomodule/output.js, test/unit/exports-nomodule/package.json, test/unit/exports-wildcard/input.js, test/unit/exports-wildcard/no.js, test/unit/exports-wildcard/node.js, test/unit/exports-wildcard/output.js, test/unit/exports-wildcard/package.json, test/unit/imports/input.js, test/unit/imports/no.js, test/unit/imports/node.js, test/unit/imports/output.js, test/unit/imports/package.json
This updates the resolver to the latest Node.js resolver handling per the modules stability with "imports" support and "exports" wildcards support.
In the API, the `"exports"` option has been renamed to `"conditions"` as it applies to both "imports" and "exports", but backwards compatibility is provided for the former exports option so this is non-breaking.
=> feat: resolve "imports" and "exports" wildcards

package.json, src/analyze.ts, src/utils/static-eval.ts, test/unit/import-meta-bad-url/asset1.txt, test/unit/import-meta-bad-url/asset2.txt, test/unit/import-meta-bad-url/input.js, test/unit/import-meta-bad-url/output.js, test/unit/import-meta-tpl-cnd/asset1.txt, test/unit/import-meta-tpl-cnd/asset2.txt, test/unit/import-meta-tpl-cnd/input.js, test/unit/import-meta-tpl-cnd/output.js, test/unit/import-meta-url/asset.txt, test/unit/import-meta-url/input.js, test/unit/import-meta-url/output.js, tsconfig.json, yarn.lock
This adds support for `import.meta.url` based asset emission in NFT.
The approach is to treat `import.meta.url` as an asset trigger, which then emits path references just like `__filename` and `__dirname`.
Support is included for `new URL('./path', import.meta.url)` patterns as well with global analysis of the `URL` object.
`pathToFileURL` and `fileURLToPath` work out without custom handling since they are effectively irrelevant in the asset emission approach used here.
Quite advanced patterns are supported, eg a test is included for the following case:
```js
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
console.log(readFileSync(
fileURLToPath(`${import.meta.url}/../${unknownCondition ? 'asset1.txt' : 'asset2.txt'}`)
).toString()); 
```
emitting both `asset1.txt` …
=> Support import.meta.url asset emission

package.json, src/resolve-dependency.ts, test/integration/sparql-builder.js, yarn.lock
It turns out there was a bug in the self resolution check which was then stopping exports resolution from working out correctly in turn.
Resolves https://github.com/vercel/nft/issues/207.
=> fix: exports resolution, fixup self resolution check

src/utils/wrappers.ts
Fixes #210
I don't have the source code to reproduce so I didn't add a test
=> fix: wrappers cannot read type of undefined

package.json, src/analyze.ts, src/types.ts, src/utils/special-cases.ts, src/utils/wrappers.ts, yarn.lock
We've had several null/undefined bugs (such as #212) that can be avoided with better TS types.
This PR adds `@types/estree` as suggested by @sokra [a few years ago](https://github.com/acornjs/acorn/issues/741#issuecomment-426260204) and this seems to do the trick.
=> fix: add missing @types/estree

src/cli.ts, test/cli.test.js
Instead of `nft build index.js && du -sh dist`, this introduces a new command: `nft size index.js`.
I also updated the CLI output to be a little friendlier:
```
△ nft 0.12.2
Usage:
$ nft [command] <file>
Commands:
build    trace and copy to the dist directory
print    trace and print to stdout
size    trace and print size in bytes
```
=> feat: add cli command `size`

package.json, src/analyze.ts, test/ecmascript.test.js, yarn.lock
This fixes numeric separators failing with `Identifier directly after number (2:10)`.
Note that numeric separators were added in ES2021 but works with Node.js 12+
=> fix: bump acorn to 8.3.0

.github/workflows/ci.yml, package.json, yarn.lock
Bump jest to the latest version and fix CI network timeout on macOS
=> chore: bump jest to 27.0.4

package.json, src/analyze.ts, src/types.ts, src/utils/special-cases.ts, src/utils/static-eval.ts, src/utils/types.ts, src/utils/wrappers.ts
Fixes consumers using TS failing with
```
Error: ../../node_modules/@vercel/nft/out/types.d.ts(3,34): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
Error: Command failed: tsc
```
This moves internal types to `./utils/types.ts` and deletes those upon publishing.
The external types will continue to live in `./types.ts`.
=> fix: remove internal types on publish

jest.config.js, prepare-install.js, src/node-file-trace.ts, src/resolve-dependency.ts, src/utils/sharedlib-emit.ts, test/integration.test.js, test/unit.test.js
This ensures we leverage the shared cache when preforming expensive checks to provide better performance when tracing multiple files individually but sharing the same cache instead of tracing them in the same `nodeFileTrace` run. 
In one test repo this brought tracing down from 130 seconds -> 25 seconds while tracing separately. which brings this much closer with the time it took when tracing all files in one `nodeFileTrace` run which was around 17 seconds.
=> Add additional items to shared cache

test/ecmascript/data-es2016plus.js, test/ecmascript/data-es5.js, test/ecmascript/data-es6.js, test/ecmascript/data-esintl.js, test/ecmascript/data-esnext.js
Update ecmascript tests from https://github.com/kangax/compat-table
=> chore: Update ecmascript tests

.github/CODEOWNERS
Luc and Timer haven't work on nft in a couple years so adding ijjk as a codeowner
=> chore: add ijjk as a codeowner

package.json, test/integration.test.js
This dependency is not necessary so we can remove it
=> fix: remove unused `mkdirp` dependency

jest.config.js, prepare-install.js, src/node-file-trace.ts, src/types.ts
Adds a type to enumerate all possible reasons
=> chore: Add TS type for `NodeFileTraceReasonType`

src/node-file-trace.ts, src/types.ts, test/unit.test.js, test/unit/multi-input/child-4.js, test/unit/multi-input/input-4.js, test/unit/multi-input/output.js, test/unit/multi-input/style.module.css
There is a scenario where a single file is both imported as a `dependency` and read as a `asset` file so we must keep track of both usages in the Reason object.
=> major: Change reason type from string to array

src/cli.ts, test/cli.test.js
This PR adds a new command, `nft why`, to the cli that will print the reason why a file was included (similar to `yarn why`)
=> feat: add `nft why` command

src/analyze.ts, src/resolve-dependency.ts, test/unit/asset-fs-array-expr-node-require/asset1.txt, test/unit/asset-fs-array-expr-node-require/input.js, test/unit/asset-fs-array-expr-node-require/output.js, test/unit/asset-fs-array-expr/input.js, test/unit/asset-fs-inline-path-enc-es-node-import/asset.txt, test/unit/asset-fs-inline-path-enc-es-node-import/input.js, test/unit/asset-fs-inline-path-enc-es-node-import/output.js
This appears to be enough to fix #284, but I'm not sure where a test would go
=> fix: handle `node:` prefix

src/utils/static-eval.ts, test/unit/ts-path-join/file.txt, test/unit/ts-path-join/input.js, test/unit/ts-path-join/output.js
=> fix: handle static eval for sequence expression (fix TS 4.4+)

prepare-install.js
Windows tests should preserve yarn.lock
In the future we might want to use `--frozen-lockfile` but for now this will prevent windows tests from inadvertently upgrading dependencies.
=> chore: windows tests should preserve yarn.lock

src/node-file-trace.ts, test/unit.test.js, test/unit/jsx-input/dep.jsx, test/unit/jsx-input/input.jsx, test/unit/jsx-input/output.js
This fixes an issue where a file input ending with `.jsx` was not traced properly.
Since we already fail gracefully for files that cannot be parsed, this PR removes the guard on all input file extensions.
- Also fixes #249
=> feat: allow all file extension inputs (including `.jsx`)

package.json, src/utils/binary-locators.ts, yarn.lock
In a previous PR (#206), support for `@mapbox/node-pre-gyp` was added and the legacy `node-pre-gyp` was kept around for backwards compatibility.
However, these packages are currently identical besides changing ES5 to ES6 (var => const) should be backwards compatible and safe to drop `node-pre-gyp`.
- [Screenshot of `lib/util/napi.js` diff](https://user-images.githubusercontent.com/229881/176289055-2b97ba77-b086-4616-b9a7-a429bcddb460.png)
- [Screenshot of `lib/util/versioning.js` diff](https://user-images.githubusercontent.com/229881/176289294-f6fc854d-f8e3-46e0-8ad6-8dd6ec599c9d.png)
This will remove the deprecation warning:
> Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
=> fix: remove `node-pre-gyp` dependency

package.json, readme.md, src/node-file-trace.ts, src/types.ts, yarn.lock
This adds concurrency limits to our `fs` calls to attempt to alleviate memory issues with too many promises being stored in memory at once. 
x-ref: [slack thread](https://vercel.slack.com/archives/CGU8HUTUH/p1657905624763969?thread_ts=1655847330.113019&cid=CGU8HUTUH)
=> fix: add concurrency limit to fs calls

package.json, src/analyze.ts, src/utils/ast-helpers.ts, src/utils/static-eval.ts, src/utils/types.ts, src/utils/wrappers.ts, yarn.lock
Part of #315
This fixes a bug where `attachScopes` didn't detect the new scope inside the for loop with shadowed variables before, resulting in later code paths possibly crashing because they expect the dependency to be of type string. No test added because as noted in #315 this doesn't thix that issue (if it even is one).
Bumping the version made a previous workaround of conflicting estree-walker versions unnecessary, but required to bring back a now-deleted type from the package
=> fix: bump rollup pluginutils version

package.json, src/analyze.ts, src/node-file-trace.ts, tsconfig.json, yarn.lock
- Set minimum node to version 14 since 12 is EOL
- Bump typescript to version 4
=> BREAKING CHANGE: set minimum node version to 14

.github/workflows/ci.yml, package.json, yarn.lock
Update CI to run against Node.js 18 and also change cancel implementation
=> chore: update ci to test node 18

src/node-file-trace.ts, src/resolve-dependency.ts, test/unit.test.js, test/unit/ts-input-esm/dep1.ts, test/unit/ts-input-esm/dep2.ts, test/unit/ts-input-esm/input.ts, test/unit/ts-input-esm/output.js, test/unit/ts-input-esm/package.json, test/unit/ts-input-esm/tsconfig.json
This PR fixes a bug where TS input was not considering ESM with `type: module` in package.json
Related to #129 which added package.json emission but only for JS input.
=> fix: TS input when targeting ESM with `type: module`

.github/workflows/ci.yml, package.json, yarn.lock
Revert lockfile from #325 and use `npx` to publish instead.
=> fix: ci publish with `npx semantic-release` instead

package.json
Fixes an error during publish:
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@vercel%2fnft - Two-factor authentication is required to publish this package but an automation token was specified
```
https://github.com/vercel/nft/actions/runs/3586279450/jobs/6035283995#step:10:494
=> fix: set `publishConfig.access=public`

src/fs.ts, src/node-file-trace.ts, test/unit.test.js
Right now the cache was only populated after the call to the fs API succeed, which in an async context was leading to multiple file IO or analyze tasks started for the same file at once. This is because both file IO are async and so until the fs call finished other calls for the same file can still come in.
To fix this I extracted all file IO calls into a separate class that wraps everything correctly and instead of caching the actual result, now a Promise is cached. So the cache now always needs to be awaited.
As the values in the cache change this is definitely a breaking change. Something like this:
```diff
const cache = {};
await nodeFileTrace([file], {
cache,
);
-const cacheValue = cache.fileCache.get(file);
+const cacheValue = await cache.fileCache.get(file);
```
I know this is …
=> fix: Make caching work correctly in async context

.github/workflows/ci.yml
Previously the `BULL_REDIS_CONNECTION` env var was a remote redis instance.
That token instance must have changed hostnames or expired because it started failing with [`getaddrinfo ENOTFOUND`](https://github.com/vercel/nft/actions/runs/5350038924/jobs/9702103910#step:7:8979).
This PR removes the need for a remote instance and instead uses github actions [service container](https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers) to starts and stop redis.
=> chore(ci): fix redis connection

readme.md, src/index.ts
nft allows you to override the resolve step with a hook however it does not expose its internal resolveDependency implementation. This means if you want to take over resolving in certain cases you must do so in every case. To make conditional or augmented resolving possible this change reexports the resolveDependency function from the index. This way you can use it in custom resolve hook implementations
=> feat(resolve): export `resolve()` function

src/resolve-dependency.ts
This feels like the better choice rather than using a private property on `repl`.
supported as of [v6.13.0](https://nodejs.org/api/module.html#modulebuiltinmodules)
=> fix: use `builtinModules` from `module`

package.json, src/node-file-trace.ts, test/integration.test.js, test/integration/vercel-edge-config-esm.js, test/integration/vercel-edge-config-esm.mjs, yarn.lock
When `nft` analyzes a file that has both a `require()` and an ESM `export`, the first call to acorn fails because of the `export`, so it treats the whole file as ESM, which is probably fine.
The problem is it treats the `require()` as an ESM import which is wrong. This will cause the resolve dependency entrypoint in the dependency to get the ESM export instead of the proper CJS export.
If the dependency is an `import`, add it to `imports`. If it's a `require()`, add it to `deps` and don't worry about whatever `isESM`.
=> fix: resolve cjs deps as cjs instead of esm

package.json, src/node-file-trace.ts, test/integration.test.js, test/integration/vercel-edge-config-esm.mjs, yarn.lock
This reverts commit 1eba4d507bcfc0d34ae51d98ed1b285dc4537923.
The fix in the original PR did solve the problem of tracing a dependency being loaded from an ESM file via `require()`, but also caused a regression where a simple `.mjs` file with ESM imports was failing. I have a test (https://github.com/vercel/nft/pull/364) for that.
=> fix: Revert "fix: resolve cjs deps as cjs instead of esm (#362)"

.github/workflows/ci.yml
Locks our python version for our macOS node 16 test job
x-ref: https://github.com/vercel/nft/actions/runs/7067408413/job/19240984319
=> chore: fix mac node 16 test job

package.json
This is a partial revert of PR https://github.com/vercel/nft/pull/374
It was dropping support for node@16 in CI but it didn't modify `target` in tsconfig.json, so 16 is still supported.
Furthermore, 16 is going to be [supported by Vercel a little longer](https://vercel.com/changelog/node-js-14-and-16-are-being-deprecated).
This fixes the warning when installing Vercel CLI using node@16
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@vercel/nft@0.26.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```
=> fix: rollback engines to `>=16`

.github/workflows/ci.yml, jest.config.js, package-lock.json, package.json, test/integration/canvas.js
This fixes an issue when a contributor (or [GH Actions](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/)) runs `npm install` using Apple Silicon which would fail since there is no precompiled arm64 binary to download for `canvas`. The error looks like this:
```
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.19.0 (node-v108 ABI, unknown) (falling back to source compile …
```
=> chore: remove canvas test

jest.config.js, package-lock.json, package.json, src/analyze.ts, test/integration/zeromq.js, test/unit.test.js, test/unit/zeromq-node-gyp/input.js, test/unit/zeromq-node-gyp/output.js
- Fixes #391 
Three things I want to point out:
1. In zeromq the way node-gyp-build is called is by passing `path.join(__dirname, "..")` instead of `__dirname` to the `require("node-gyp-build")(...)` call.
2. In zeromq they use `@aminya/node-gyp-build` instead of `node-gyp-build`, particular-li version `4.5.0-aminya.5`.
3. The zeromq version that's recommended for new project is the `6` which is beta according to @aminya https://github.com/zeromq/zeromq.js.
After those changes it resolves OK.
```
❯ node ./node_modules/@vercel/nft/out/cli.js print ./node_modules/zeromq/lib/index.js
FILELIST:
node_modules/@aminya/node-gyp-build/index.js
node_modules/@aminya/node-gyp-build/package.json
node_modules/zeromq/lib/draft.js
node_modules/zeromq/lib/index.js
node_modules/zeromq/lib/native.js …
```
=> fix(analyze): node-gyp-build not including zeromq prebuilds

.git-blame-ignore-revs
This will make git history easier to understand since the previous commit (c16e7945c3f3221616567356d9abc2e824bf38cd) changed every line
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
=> chore: ignore formatting change in git blame

readme.md
I just added parentheses to the functions that were missing them.
**Old:**
```js
const { fileList } = await nodeFileTrace(files, {
base: process.cwd()
}
```
```js
const { fileList } = await nodeFileTrace(files, {
processCwd: path.resolve(__dirname)
}
```
**New:**
```js
const { fileList } = await nodeFileTrace(files, {
base: process.cwd()
});
```
```js
const { fileList } = await nodeFileTrace(files, {
processCwd: path.resolve(__dirname)
});
```
=> chore(readme): Add parentheses to the end of functions in readme

package-lock.json, package.json, src/utils/special-cases.ts, test/integration/serialport.js
Tested with prebuilds and compiling serialport from source
=> fix: Add special case for Serial Port binary (.node) modules

package-lock.json, package.json, src/utils/special-cases.ts, test/integration/geoip-lite.js
Currently, nft can not handle data assets of `geoip-lite` package properly. Error message like below ⬇️
Test Code
```js
const geoip = require('geoip-lite');
const ip = "207.97.227.239";
const geo = geoip.lookup(ip);
```
This PR adds essential data files as assets for `geoip-lite` in special-case to solve it.
=> fix: add special case for `geoip-lite`

test/ecmascript.test.js, test/ecmascript/data-es2016plus.js, test/ecmascript/data-es5.js, test/ecmascript/data-es6.js, test/ecmascript/data-esintl.js, test/ecmascript/data-esnext.js
This PR updates the ecmascript tests using the instructions here:
https://github.com/vercel/nft/blob/main/test/ecmascript/README.md
We are currently failing a couple new test categories, `RegExp Pattern Modifiers` (stage 4) and `Duplicate named capturing groups` (stage 3), so those are skipped for now.
In a future PR, we can try updating `acorn` to see if fixes those tests.
=> chore(test): update ecmascript tests

package-lock.json, package.json
- Related to https://github.com/vercel/nft/issues/421
=> fix: bump `@mapbox/node-pre-gyp@1.0.11`

package-lock.json, package.json
Allows it to dedupe with the version most people would have in their projects if they're using rollup
=> fix: bump @rollup/plugin-utils to 5.1.3

package-lock.json, package.json
closes https://github.com/vercel/nft/issues/421
it's taken me almost 6 months from starting in https://github.com/vercel/nft/issues/421#issuecomment-2195148286, but this finally fixes it!
=> chore: upgrade node-pre-gyp to fix deprecation warnings

src/analyze.ts, src/test.ts, src/utils/static-eval.ts, src/utils/types.ts, test/unit/url-error/input.js, test/unit/url-error/output.js
`nodeFileTrace` errors on `const URLParser = typeof window === 'undefined' ? URL : 'b'` with `TypeError: Class constructor URL cannot be invoked without 'new'`.
This is because this code:
```ts
async function ConditionalExpression() {
return {
test: 'foo',
then: URL,
else: 'bar',
};
}
await ConditionalExpression();
```
calls `URL()` since `ConditionalExpression` is an async function returning a [thenable](https://masteringjs.io/tutorials/fundamentals/thenable).
Solution: rename all `.then` fields to `.ifTrue` since `then` is reserved for thenables.
Closes https://github.com/vercel/nft/pull/447
=> fix: avoid URL illegal constructor error

src/analyze.ts, test/unit/module-create-require/input.js, test/unit/module-create-require/lib.node, test/unit/module-create-require/output.js
Added support for tracing dependencies loaded via `module.createRequire`.
Fixes #430
=> feat: support `module.createRequire`

package-lock.json, package.json
@mapbox/node-pre-gyp just released their version 2 a few days ago, this pull request simply bumps rc to stable v2
=> fix: bump @mapbox/node-pre-gyp

.github/workflows/ci.yml
Fix CI due to corepack issue:
- https://github.com/nodejs/corepack/issues/612
The solution is to set `COREPACK_DEFAULT_TO_LATEST=0` as suggested here:
- https://github.com/nodejs/corepack/issues/625#issuecomment-2630065183
This works since we pin the version of pnpm in package.json and don't rely on corepack fetching the latest pnpm version.
=> chore(ci): fix corepack

package-lock.json, package.json, src/analyze.ts, src/utils/sharedlib-emit.ts
closes #389
`glob` v7 is deprecated. Switching to `tinyglobby` would be nicer, but I haven't quite figured that one out yet
=> chore: upgrade glob

.github/PULL_REQUEST_TEMPLATE.md
The actual PR for glob upgrade is https://github.com/vercel/nft/pull/505
Adding these notes as I think it's not the first time I've made this mistake and there's not really a way for contributors to know at the moment
=> fix: upgrade to glob 10
