vercel/nft

.github/CODEOWNERS
This will make sure we are assigned as reviewers for any PRs
=> Add github codeowners

package.json, test/integration.test.js
Maybe we can make tests run in parallel again.
=> Run tests in parallel

.kodiak.toml
This will allow automerging a PR with a label.
=> Add automerge config

package.json, src/utils/special-cases.js, test/unit/phantomjs-prebuilt/input.js, test/unit/phantomjs-prebuilt/output.js, yarn.lock
=> Fix `phantomjs-prebuilt` binary

package.json, src/analyze.js, test/ecmascript.test.js, yarn.lock
=> Fix optional catch binding

readme.md, src/node-file-trace.js, src/resolve-dependency.js, test/unit.test.js, test/unit/esm-paths-trailer/esm-dep.js, test/unit/esm-paths-trailer/input.js, test/unit/esm-paths-trailer/output.js, test/unit/esm-paths/esm-dep.js, test/unit/esm-paths/input.js, test/unit/esm-paths/output.js
This implements a simple paths implementation for easier integration into other workflows.
We could also implement a full resolve hook option here as well, but this seemed somewhat simpler for now.
=> Paths implementation

node-file-trace.d.ts
This adds updates the typings for the features from the recent PRs.
=> Add types for new features

package.json, src/analyze.js, test/integration/passport-trakt.js, test/unit/pkginfo/output.js, yarn.lock
Fixes https://github.com/zeit/node-file-trace/issues/95 which was caused by an error in the `pkginfo` package.json lookup inlining logic.
=> Fix `passport-trakt` recursive resolve

package.json, prepare-install.js, src/analyze.js, src/utils/special-cases.js, test/integration/yoga-layout.js, yarn.lock
This ports the 12 CI fixes from https://github.com/zeit/ncc/pull/525 and bumps dependencies
=> Fix Node 12 CI (from ncc)

src/utils/wrappers.js, test/unit/jsonc-parser-wrapper/dep.js, test/unit/jsonc-parser-wrapper/input.js, test/unit/jsonc-parser-wrapper/output.js
Fixes https://github.com/zeit/node-file-trace/issues/107.
=> Support jsonc-style wrapper

package.json, readme.md
We renamed to the GitHub org to `vercel`
=> Update repo from zeit to vercel

package.json, src/utils/wrappers.js, test/integration/paraphrase.js, test/unit/webpack-wrapper-null/input.js, test/unit/webpack-wrapper-null/mangled.js, test/unit/webpack-wrapper-null/output.js, yarn.lock
=> Fix null check in paraphrase wrappers

jest.config.js
This will fail CI if we drop below 95% coverage
=> Bump test coverage to 95%

test/ecmascript.test.js
=> fix: test optional chaining

src/utils/wrappers.ts, test/unit/browserify-minify/input.js, test/unit/browserify-minify/output.js
Fixes https://github.com/vercel/nft/issues/161.
This updates the browserify wrapper handling to cater to the new minification variants.
=> fix: minified browserify wrapper handling

package.json, src/analyze.ts, src/utils/static-eval.ts, test/unit/require-var-branch/input.js, test/unit/require-var-branch/lib1/createsend.js, test/unit/require-var-branch/lib2/createsend.js, test/unit/require-var-branch/output.js, tsconfig.json, yarn.lock
This adds support for branching variables in analysis, tracing those branched bindings through the known bindings and in further subsequent analysis.
Fixes https://github.com/vercel/nft/issues/175.
The approach didn't end up too costly and seems fairly useful actually.
=> Support require variable branching

.github/workflows/ci.yml, package.json, yarn.lock
=> Deps: Bump codecov to 3.8.1

src/analyze.ts, test/unit/top-level-await/input.js, test/unit/top-level-await/module.js, test/unit/top-level-await/output.js
=> feat: allow await outside function

package.json, src/utils/special-cases.ts, test/integration/playwright-core.js
Verified that the test was failing without the special case and it's passing with the special case.
Closes #184
Closes #211
Relates https://github.com/microsoft/playwright/issues/5862
=> fix: add playwright-core support

package.json, src/utils/special-cases.ts, test/integration.test.js, test/integration/esbuild.js, yarn.lock
- Fixes #246 
- Related to https://github.com/vercel/vercel/issues/7287
- Related to https://github.com/vercel/next.js/issues/33294
=> Add special case for `esbuild`

.github/workflows/ci.yml
=> Revert "fix: install with `yarn add --dev` in ci"

.github/workflows/pr.yml
This makes sure the PR title is valid and thus can auto-release once merged to main.
=> ci: lint pr title

src/node-file-trace.ts, src/utils/types.ts
No logical change here - just some cleanup
=> chore: fix types

.github/CODEOWNERS
Adding @vercel/vercel-cli-admins to codeowners
=> chore(ci): add cli team as codeowners

test/integration/axios.js
Fixes a test failure
```
AxiosError: Request failed with status code 503
```
https://github.com/vercel/nft/actions/runs/9785119974/job/27017473162?pr=429#step:10:1864
=> chore(test): change axios test url

test/cli.test.js
x-ref: https://github.com/vercel/nft/pull/453#issuecomment-2529266471
=> fix: trigger release

package-lock.json, package.json, src/node-file-trace.ts
This removes 5 dependencies from the dependency tree
=> fix: reduce number of dependencies

package-lock.json, package.json, src/utils/static-eval.ts, tsconfig.json
- Closes https://github.com/vercel/nft/issues/457
=> feat: bump engines.node>=18 and target=es2022

test/integration/isomorphic-unfetch.js, test/integration/request.js
=> chore(test): fix tests fetch/request/etc

package-lock.json, package.json, test/integration/lighthouse.js
=> chore: Bump lighthouse from ^5 to ^12

package-lock.json, package.json
=> chore: Bump bull to ^4

.github/workflows/ci.yml
See npm docs https://docs.npmjs.com/generating-provenance-statements
See semantic-release docs https://github.com/semantic-release/npm/blob/master/README.md#npm-provenance
=> fix(ci): publish to npm with provenance

package-lock.json, package.json
Confirming latest version of sharp works with integration tests
=> chore(devDep): bump sharp test
